services:
  website:
    image: ghcr.io/pinjron/compliments
    # build:
    #   context: .
    #   target: ruby
    command: bundle exec ruby app.rb -p 3000
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    stdin_open: true
    tty: true
    volumes:
      - db:/app/db_data/:rw

volumes:
  db: