services:
  website:
    image: ghcr.io/pinjron/compliments
    container_name: "site"
    environment:
       SECRET_KEY_BASE: /run/secrets/secret_key_base
    command: bundle exec rails s -b 0.0.0.0
    stdin_open: true
    tty: true
    volumes:
      - db:/app/db_data/:rw
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=traefik-public"
    - "traefik.http.routers.qwe.rule=Host(`wol.dizeldigital.ru`)"
    - "traefik.http.routers.qwe.entrypoints=websecure"
    - "traefik.http.routers.qwe.tls.certresolver=myresolver"
    - "traefik.http.services.qwe.loadbalancer.server.port=3000"
    secrets:
      - secret_key_base
    networks:
      - traefik-public


  migration:
    restart: on-failure
    image: ghcr.io/pinjron/compliments
    container_name: "migrations"
    environment:
       SECRET_KEY_BASE: /run/secrets/secret_key_base
    command: bundle exec rails db:prepare
    stdin_open: true
    tty: true
    volumes:
      - db:/app/db_data/:rw
    secrets:
      - secret_key_base

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--providers.docker.swarmMode=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=dimitry.zelencko@yandex.ru"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  db:
  letsencrypt:

secrets:
  secret_key_base:
    external: true

networks:
  traefik-public:
    external: true