# config/database.yml
default: &default
  adapter: sqlite3
  encoding: unicode
  database: db_data/foo.sqlite3
  pool: 5
  timeout: 5000
  # host: db

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
