name: Deploy staging

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login
      env:
        CR_PAT: ${{ secrets.DOCKER_REGESTRY_TOKEN }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u PinJron --password-stdin

    - name: Build the Docker image
      run: |
        docker build . -t ghcr.io/pinjron/compliments:latest --target ruby

    - name: Push docker image
      run: |
        docker push ghcr.io/pinjron/compliments:latest

    - name: Setup shh credentials
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.STAGING_SSH_KNOWN_HOSTS }}
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

    - name: Deploy image
      env:
        DOCKER_HOST: ssh://root@dizeldigital.ru
      run: |
        docker stack deploy --compose-file ${{ github.workspace }}/docker-compose-prod.yml --with-registry-auth gtm-compliments
        docker system prune -a --volumes