name: Deploy staging

on:
  workflow_dispatch:

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        KEY: ${{ secrets.PRODUCTION_KEY }}
      run: |
        echo -n $KEY > ${{ github.workspace }}/config/production.key
        docker build -t ghcr.io/emfy0/gtm_app:latest .

    - name: Push docker image
      env:
        CR_PAT: ${{ secrets.DOCKER_REGESTRY_TOKEN }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u emfy0 --password-stdin
        docker push ghcr.io/emfy0/gtm_app:latest

    - name: Setup shh credentials
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.STAGING_SSH_KNOWN_HOSTS }}
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa

    - name: Deploy image
      env:
        DOCKER_HOST: ssh://${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}
      run: |
        docker stack deploy --compose-file ${{ github.workspace }}/docker-compose.yml --with-registry-auth gtm-eng